spring:
  profiles:
    active:
    - dev
---
server: 
  port: 7001 
spring:
  profiles: dev
  application: 
    name: microservice-cloud-configed-eureka-server
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost.com:7001/eureka/   
---
server: 
  port: 7001 
spring:
  profiles: test
  application: 
    name: microservice-cloud-configed-eureka-server
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:7001/eureka/